fixup! release: create initial Windows installer build workflow

diff --git a/.github/workflows/build-git-installers.yml b/.github/workflows/build-git-installers.yml
--- a/.github/workflows/build-git-installers.yml
+++ b/.github/workflows/build-git-installers.yml
@@ -23,8 +23,8 @@ jobs:
       - name: Validate tag
         run: |
           echo "$GITHUB_REF" |
-          grep -E '^refs/tags/v2\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.vfs\.0\.(0|[1-9][0-9]*)(\.rc[0-9])?$' || {
-            echo "::error::${GITHUB_REF#refs/tags/} is not of the form v2.<X>.<Y>.vfs.0.<W>[.rc<N>]" >&2
+            grep -E '^refs/tags/v2\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-rc[0-9]+)?\.vfs\.0\.(0|[1-9][0-9]*)$' || {
+            echo "::error::${GITHUB_REF#refs/tags/} is not of the form v2.<X>.<Y>[-rc<N>].vfs.0.<W>" >&2
             exit 1
           }
       - name: Determine tag to build
@@ -50,7 +50,10 @@ jobs:
           # Verify tag follows rules in GIT-VERSION-GEN (i.e., matches the specified "DEF_VER" in
           # GIT-VERSION-FILE) and matches tag determined from trigger
           make GIT-VERSION-FILE
-          test "${{ steps.tag.outputs.version }}" == "$(sed -n 's/^GIT_VERSION *= *//p'< GIT-VERSION-FILE)" || die "GIT-VERSION-FILE tag ($(cat GIT-VERSION-FILE)) does not match ${{ steps.tag.outputs.name }}"
+          expected_version="${{ steps.tag.outputs.version }}"
+          # Convert -rc to .rc to match GIT-VERSION-FILE format
+          expected_version="${expected_version//-rc/.rc}"
+          test "$expected_version" == "$(sed -n 's/^GIT_VERSION *= *//p'< GIT-VERSION-FILE)" || die "GIT-VERSION-FILE tag ($(cat GIT-VERSION-FILE)) does not match ${{ steps.tag.outputs.name }}"
   # End check prerequisites for the workflow
 
   # Build Windows installers (x86_64 & aarch64; installer & portable)
